runtime: nodejs20
basic_scaling:
  max_instances: 1
handlers:
  - url: /assets
    static_dir: build/assets
build_env_variables:
  # disable build script (pre-built before deploy)
  GOOGLE_NODE_RUN_SCRIPTS: ''
  GOOGLE_APPLICATION_CREDENTIALS: 'var/firestore.json'
